### ISSUE TITLE
Parcelable Error 

### ISSUE THREAD

**Issue by encima** [david-pugh-gcell/GCellBeaconScanner_Android_v2#1]
I get this error only on v2, v1 works fine.

> Caused by: android.os.BadParcelableException: Parcelable protocol requires a Parcelable.Creator object called CREATOR on class com.gcell.ibeacon.gcellbeaconscanlibrary.GCellPermissionSettings
                                                       at android.os.Parcel.readParcelableCreator(Parcel.java:2436)
                                                       at android.os.Parcel.readParcelable(Parcel.java:2358)
                                                       at android.os.Parcel.readValue(Parcel.java:2264)
                                                       at android.os.Parcel.readArrayMapInternal(Parcel.java:2614)
                                                       at android.os.BaseBundle.unparcel(BaseBundle.java:224)
                                                       at android.os.BaseBundle.containsKey(BaseBundle.java:273)
                                                       at android.content.Intent.hasExtra(Intent.java:5174)
                                                       at com.gcell.ibeacon.gcellbeaconscanlibrary.GCellDialogActivity.onCreate(GCellDialogActivity.java:36)
                                                       at android.app.Activity.performCreate(Activity.java:6323)
                                                       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492) 
                                                       at android.app.ActivityThread.access$900(ActivityThread.java:153) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:148) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5458) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628) 
03-13 23:02:03.562 22705-22705/? I/Process: Sending signal. PID: 22705 SIG: 9

From some digging, it seems like it could be when Proguard renames things on release? v1 seems fine so sticking with that for now. I get this on the sample project and also when adding to my own projects.

**Comment by david-pugh-gcell** [comment]
Cheers, just trying to recreate and solve!

**Comment by david-pugh-gcell** [comment]
To confirm I am not seeing this will source code, only when compiled as aar. Switching off Proguard seems to have no effect - will continue testing and report when fully investigated.

**Comment by encima** [comment]
Thanks, happy to take a look if the source is in a separate repo?

**Comment by david-pugh-gcell** [comment]
New push with updated aar version with revised rules/settings - now v2-03. This has eliminated the issue on the tests here - let me know if there are any problems.
